# Generated by Django 4.1.6 on 2023-02-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('editora', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_cadastro', models.DateField()),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
    ]
