# Generated by Django 4.1.6 on 2023-02-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('usuario', models.CharField(max_length=100)),
                ('data_emprestimo', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='emprestimo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='emprestimos.emprestimo'),
            preserve_default=False,
        ),
    ]
